name: socorre_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  bot_toast: ^4.1.3
  phosphor_flutter: ^2.1.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2
  get_it: ^7.7.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  shared_preferences: ^2.2.3
  brasil_fields: ^1.15.0
  search_cep: ^4.0.2
  intl: ^0.19.0

flutter_native_splash:
  image: "assets/images/logo-splash.png"
  background_image: "assets/images/splash.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/images/launcher-back.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/launcher-no-back.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
